### ISSUE TITLE
Integrate with Views Bulk Operations

### ISSUE THREAD

**Issue by iamEAP** [tableau-mkt-archived/entity_xliff_ftp#3]
Would be lovely to be able to create a Views Bulk Operations view of translatable entities, check off a few entities, select the desired target languages, and click a button to push all XLIFFs to the remote server.

**Comment by iamEAP** [comment]
@angrytoast @pvanoverbeek Bumping the priority on this, as it would save LOC quite a bit of time for more recent content types (drivers, release notes, etc).

**Comment by angrytoast** [comment]
This actually sounds pretty interesting, I might take this one

**Comment by pvanoverbeek** [comment]
Thanks guys!
